### PR TITLE
Remove TaskWrap usage, since it's handled in trailblazer-activity

### PR DESCRIPTION
**Pull request by marctich**
@apotonick removed TaskWrap in https://github.com/trailblazer/trailblazer-operation/commit/5e56fc19e1c5be3002203c14c0c75d49056b1652 but forgot to remove the rest of it.

### CODE REVIEW

**Comment by apotonick** [comment]
Awesome, thanks!

**Comment by marctich** [comment]
Just a thought, but wouldn't it be nicer to be able to do:

Operation::Create do
on(:success) { |result| puts result[:model].inspect }
on(:pass_fast) { |result| puts result[:model].inspect }
on(:failure) { |result| puts result[:errors].inspect }
on(:fail_fast) { |result| puts result[:errors].inspect }
end

Marc Tichelaar

E: m.tichelaar@gmail.com (https://link.getmailspring.com/link/local-95ef2554-117e@marc-pc/0?redirect=mailto%3Am.tichelaar%40gmail.com&recipient=reply%2B001bb2c2795b8a951c7a5afdb96bc2336d840ee9d9703bea92cf00000001166d910392a169ce111fda0c%40reply.github.com)
P: +31 6 215 00 00 4 (tel:+31%206%20215%2000%2000%204?recipient=reply%2B001bb2c2795b8a951c7a5afdb96bc2336d840ee9d9703bea92cf00000001166d910392a169ce111fda0c%40reply.github.com)

**Comment by apotonick** [comment]
This is one of the features `endpoint` will bring!

**Comment by marctich** [comment]
Wasn't supposed to be here though, meant to mail you personally ;)

**Pull request merged**
